import {
	MILLISECOND_UNPADDED,
	MILLISECOND_PADDED_3,
	FRACTIONAL_SECONDS_IDENTICAL_TO_SSS,
	FRACTIONAL_SECONDS_PADDED_2,
	FRACTIONAL_SECONDS_SINGLE_DIGIT,
	SECOND_UNPADDED,
	SECOND_PADDED_2,
	MINUTE_UNPADDED,
	MINUTE_PADDED_2,
	HOUR_12_UNPADDED,
	HOUR_12_PADDED_2,
	HOUR_24_UNPADDED,
	HOUR_24_PADDED_2,
	NARROW_OFFSET,
	SHORT_OFFSET,
	TECHIE_OFFSET,
	ABBREVIATED_NAMED_OFFSET,
	UNABBREVIATED_NAMED_OFFSET,
	IANA_ZONE,
	MERIDIEM,
	DAY_OF_MONTH_UNPADDED,
	DAY_OF_MONTH_PADDED_2,
	DAY_OF_WEEK_NUMBER,
	DAY_OF_WEEK_ABBREVIATED,
	DAY_OF_WEEK_UNABBREVIATED,
	DAY_OF_WEEK_SINGLE_LETTER,
	MONTH_UNPADDED,
	MONTH_PADDED_2,
	MONTH_ABBREVIATED,
	MONTH_UNABBREVIATED,
	MONTH_SINGLE_LETTER,
	YEAR_UNPADDED,
	YEAR_TWO_DIGIT,
	YEAR_PADDED_4,
	ERA_ABBREVIATED,
	ERA_UNABBREVIATED,
	ERA_SINGLE_LETTER,
	ISO_WEEK_YEAR_UNPADDED,
	ISO_WEEK_YEAR_PADDED_4,
	ISO_WEEK_NUMBER_UNPADDED,
	ISO_WEEK_NUMBER_PADDED_2,
	LOCAL_WEEK_YEAR_UNPADDED,
	LOCAL_WEEK_YEAR_PADDED_4,
	LOCAL_WEEK_NUMBER_UNPADDED,
	LOCAL_WEEK_NUMBER_PADDED_2,
	ORDINAL_DAY_OF_YEAR_UNPADDED,
	ORDINAL_DAY_OF_YEAR_PADDED_3,
	QUARTER_UNPADDED,
	QUARTER_PADDED_2,
	LOCALIZED_NUMERIC_DATE,
	LOCALIZED_DATE_ABBREVIATED_MONTH,
	LOCALIZED_DATE_FULL_MONTH,
	LOCALIZED_DATE_FULL_MONTH_WEEKDAY,
	LOCALIZED_TIME,
	LOCALIZED_TIME_WITH_SECONDS,
	LOCALIZED_TIME_SECONDS_ABBREVIATED_OFFSET,
	LOCALIZED_TIME_SECONDS_FULL_OFFSET,
	LOCALIZED_24_HOUR_TIME,
	LOCALIZED_24_HOUR_TIME_WITH_SECONDS,
	LOCALIZED_24_HOUR_TIME_SECONDS_ABBREVIATED_OFFSET,
	LOCALIZED_24_HOUR_TIME_SECONDS_FULL_OFFSET,
	SHORT_LOCALIZED_DATE_TIME,
	LESS_SHORT_LOCALIZED_DATE_TIME,
	VERBOSE_LOCALIZED_DATE_TIME,
	EXTRA_VERBOSE_LOCALIZED_DATE_TIME,
	SHORT_LOCALIZED_DATE_TIME_WITH_SECONDS,
	LESS_SHORT_LOCALIZED_DATE_TIME_WITH_SECONDS,
	VERBOSE_LOCALIZED_DATE_TIME_WITH_SECONDS,
	EXTRA_VERBOSE_LOCALIZED_DATE_TIME_WITH_SECONDS,
	UNIX_TIMESTAMP_SECONDS,
	UNIX_TIMESTAMP_MILLISECONDS,
} from '../constants/formats.js'
import {
	VAR_MILLISECOND_UNPADDED,
	VAR_MILLISECOND_PADDED_3,
	VAR_FRACTIONAL_SECONDS_IDENTICAL_TO_SSS,
	VAR_FRACTIONAL_SECONDS_PADDED_2,
	VAR_FRACTIONAL_SECONDS_SINGLE_DIGIT,
	VAR_SECOND_UNPADDED,
	VAR_SECOND_PADDED_2,
	VAR_MINUTE_UNPADDED,
	VAR_MINUTE_PADDED_2,
	VAR_HOUR_12_UNPADDED,
	VAR_HOUR_12_PADDED_2,
	VAR_HOUR_24_UNPADDED,
	VAR_HOUR_24_PADDED_2,
	VAR_NARROW_OFFSET,
	VAR_SHORT_OFFSET,
	VAR_TECHIE_OFFSET,
	VAR_ABBREVIATED_NAMED_OFFSET,
	VAR_UNABBREVIATED_NAMED_OFFSET,
	VAR_IANA_ZONE,
	VAR_MERIDIEM,
	VAR_DAY_OF_MONTH_UNPADDED,
	VAR_DAY_OF_MONTH_PADDED_2,
	VAR_DAY_OF_WEEK_NUMBER,
	VAR_DAY_OF_WEEK_ABBREVIATED,
	VAR_DAY_OF_WEEK_UNABBREVIATED,
	VAR_DAY_OF_WEEK_SINGLE_LETTER,
	VAR_MONTH_UNPADDED,
	VAR_MONTH_PADDED_2,
	VAR_MONTH_ABBREVIATED,
	VAR_MONTH_UNABBREVIATED,
	VAR_MONTH_SINGLE_LETTER,
	VAR_YEAR_UNPADDED,
	VAR_YEAR_TWO_DIGIT,
	VAR_YEAR_PADDED_4,
	VAR_ERA_ABBREVIATED,
	VAR_ERA_UNABBREVIATED,
	VAR_ERA_SINGLE_LETTER,
	VAR_ISO_WEEK_YEAR_UNPADDED,
	VAR_ISO_WEEK_YEAR_PADDED_4,
	VAR_ISO_WEEK_NUMBER_UNPADDED,
	VAR_ISO_WEEK_NUMBER_PADDED_2,
	VAR_LOCAL_WEEK_YEAR_UNPADDED,
	VAR_LOCAL_WEEK_YEAR_PADDED_4,
	VAR_LOCAL_WEEK_NUMBER_UNPADDED,
	VAR_LOCAL_WEEK_NUMBER_PADDED_2,
	VAR_ORDINAL_DAY_OF_YEAR_UNPADDED,
	VAR_ORDINAL_DAY_OF_YEAR_PADDED_3,
	VAR_QUARTER_UNPADDED,
	VAR_QUARTER_PADDED_2,
	VAR_LOCALIZED_NUMERIC_DATE,
	VAR_LOCALIZED_DATE_ABBREVIATED_MONTH,
	VAR_LOCALIZED_DATE_FULL_MONTH,
	VAR_LOCALIZED_DATE_FULL_MONTH_WEEKDAY,
	VAR_LOCALIZED_TIME,
	VAR_LOCALIZED_TIME_WITH_SECONDS,
	VAR_LOCALIZED_TIME_SECONDS_ABBREVIATED_OFFSET,
	VAR_LOCALIZED_TIME_SECONDS_FULL_OFFSET,
	VAR_LOCALIZED_24_HOUR_TIME,
	VAR_LOCALIZED_24_HOUR_TIME_WITH_SECONDS,
	VAR_LOCALIZED_24_HOUR_TIME_SECONDS_ABBREVIATED_OFFSET,
	VAR_LOCALIZED_24_HOUR_TIME_SECONDS_FULL_OFFSET,
	VAR_SHORT_LOCALIZED_DATE_TIME,
	VAR_LESS_SHORT_LOCALIZED_DATE_TIME,
	VAR_VERBOSE_LOCALIZED_DATE_TIME,
	VAR_EXTRA_VERBOSE_LOCALIZED_DATE_TIME,
	VAR_SHORT_LOCALIZED_DATE_TIME_WITH_SECONDS,
	VAR_LESS_SHORT_LOCALIZED_DATE_TIME_WITH_SECONDS,
	VAR_VERBOSE_LOCALIZED_DATE_TIME_WITH_SECONDS,
	VAR_EXTRA_VERBOSE_LOCALIZED_DATE_TIME_WITH_SECONDS,
	VAR_UNIX_TIMESTAMP_SECONDS,
	VAR_UNIX_TIMESTAMP_MILLISECONDS,
} from '../constants/variables.js'

export class FormatToken {
	public variableId: string
	public value: string
	public description: string

	constructor(variableId: string, value: string, description: string) {
		this.variableId = variableId
		this.value = value
		this.description = description
	}
}

export const FormatTokens: Array<FormatToken> = [
	{ variableId: VAR_MILLISECOND_UNPADDED, value: MILLISECOND_UNPADDED, description: 'millisecond, unpadded' },
	{ variableId: VAR_MILLISECOND_PADDED_3, value: MILLISECOND_PADDED_3, description: 'millisecond, padded to 3' },
	{
		variableId: VAR_FRACTIONAL_SECONDS_IDENTICAL_TO_SSS,
		value: FRACTIONAL_SECONDS_IDENTICAL_TO_SSS,
		description: 'fractional seconds, functionally identical to SSS',
	},
	{
		variableId: VAR_FRACTIONAL_SECONDS_PADDED_2,
		value: FRACTIONAL_SECONDS_PADDED_2,
		description: 'fractional seconds, between 0 and 99, padded to 2',
	},
	{
		variableId: VAR_FRACTIONAL_SECONDS_SINGLE_DIGIT,
		value: FRACTIONAL_SECONDS_SINGLE_DIGIT,
		description: 'fractional seconds, between 0 and 9',
	},
	{ variableId: VAR_SECOND_UNPADDED, value: SECOND_UNPADDED, description: 'second, unpadded' },
	{ variableId: VAR_SECOND_PADDED_2, value: SECOND_PADDED_2, description: 'second, padded to 2' },
	{ variableId: VAR_MINUTE_UNPADDED, value: MINUTE_UNPADDED, description: 'minute, unpadded' },
	{ variableId: VAR_MINUTE_PADDED_2, value: MINUTE_PADDED_2, description: 'minute, padded to 2' },
	{ variableId: VAR_HOUR_12_UNPADDED, value: HOUR_12_UNPADDED, description: 'hour, in 12-hour time, unpadded' },
	{ variableId: VAR_HOUR_12_PADDED_2, value: HOUR_12_PADDED_2, description: 'hour, in 12-hour time, padded to 2' },
	{ variableId: VAR_HOUR_24_UNPADDED, value: HOUR_24_UNPADDED, description: 'hour, in 24-hour time, unpadded' },
	{ variableId: VAR_HOUR_24_PADDED_2, value: HOUR_24_PADDED_2, description: 'hour, in 24-hour time, padded to 2' },
	{ variableId: VAR_NARROW_OFFSET, value: NARROW_OFFSET, description: 'narrow offset' },
	{ variableId: VAR_SHORT_OFFSET, value: SHORT_OFFSET, description: 'short offset' },
	{ variableId: VAR_TECHIE_OFFSET, value: TECHIE_OFFSET, description: 'techie offset' },
	{
		variableId: VAR_ABBREVIATED_NAMED_OFFSET,
		value: ABBREVIATED_NAMED_OFFSET,
		description: 'abbreviated named offset',
	},
	{
		variableId: VAR_UNABBREVIATED_NAMED_OFFSET,
		value: UNABBREVIATED_NAMED_OFFSET,
		description: 'unabbreviated named offset',
	},
	{ variableId: VAR_IANA_ZONE, value: IANA_ZONE, description: 'IANA zone' },
	{ variableId: VAR_MERIDIEM, value: MERIDIEM, description: 'meridiem' },
	{ variableId: VAR_DAY_OF_MONTH_UNPADDED, value: DAY_OF_MONTH_UNPADDED, description: 'day of the month, unpadded' },
	{ variableId: VAR_DAY_OF_MONTH_PADDED_2, value: DAY_OF_MONTH_PADDED_2, description: 'day of the month, padded to 2' },
	{
		variableId: VAR_DAY_OF_WEEK_NUMBER,
		value: DAY_OF_WEEK_NUMBER,
		description: 'day of the week, as number from 1-7 (Monday is 1, Sunday is 7)',
	},
	{
		variableId: VAR_DAY_OF_WEEK_ABBREVIATED,
		value: DAY_OF_WEEK_ABBREVIATED,
		description: 'day of the week, as an abbreviate localized string',
	},
	{
		variableId: VAR_DAY_OF_WEEK_UNABBREVIATED,
		value: DAY_OF_WEEK_UNABBREVIATED,
		description: 'day of the week, as an unabbreviated localized string',
	},
	{
		variableId: VAR_DAY_OF_WEEK_SINGLE_LETTER,
		value: DAY_OF_WEEK_SINGLE_LETTER,
		description: 'day of the week, as a single localized letter',
	},
	{ variableId: VAR_MONTH_UNPADDED, value: MONTH_UNPADDED, description: 'month, unpadded' },
	{ variableId: VAR_MONTH_PADDED_2, value: MONTH_PADDED_2, description: 'month, padded to 2' },
	{
		variableId: VAR_MONTH_ABBREVIATED,
		value: MONTH_ABBREVIATED,
		description: 'month, as an abbreviated localized string',
	},
	{
		variableId: VAR_MONTH_UNABBREVIATED,
		value: MONTH_UNABBREVIATED,
		description: 'month, as an unabbreviated localized string',
	},
	{
		variableId: VAR_MONTH_SINGLE_LETTER,
		value: MONTH_SINGLE_LETTER,
		description: 'month as a single localized letter',
	},
	{ variableId: VAR_YEAR_UNPADDED, value: YEAR_UNPADDED, description: 'year, unpadded' },
	{ variableId: VAR_YEAR_TWO_DIGIT, value: YEAR_TWO_DIGIT, description: 'year, two-digit' },
	{ variableId: VAR_YEAR_PADDED_4, value: YEAR_PADDED_4, description: 'year, four- to six-digit, padded to 4' },
	{ variableId: VAR_ERA_ABBREVIATED, value: ERA_ABBREVIATED, description: 'abbreviated localized era' },
	{ variableId: VAR_ERA_UNABBREVIATED, value: ERA_UNABBREVIATED, description: 'unabbreviated localized era' },
	{ variableId: VAR_ERA_SINGLE_LETTER, value: ERA_SINGLE_LETTER, description: 'one-letter localized era' },
	{ variableId: VAR_ISO_WEEK_YEAR_UNPADDED, value: ISO_WEEK_YEAR_UNPADDED, description: 'ISO week year, unpadded' },
	{ variableId: VAR_ISO_WEEK_YEAR_PADDED_4, value: ISO_WEEK_YEAR_PADDED_4, description: 'ISO week year, padded to 4' },
	{
		variableId: VAR_ISO_WEEK_NUMBER_UNPADDED,
		value: ISO_WEEK_NUMBER_UNPADDED,
		description: 'ISO week number, unpadded',
	},
	{
		variableId: VAR_ISO_WEEK_NUMBER_PADDED_2,
		value: ISO_WEEK_NUMBER_PADDED_2,
		description: 'ISO week number, padded to 2',
	},
	{
		variableId: VAR_LOCAL_WEEK_YEAR_UNPADDED,
		value: LOCAL_WEEK_YEAR_UNPADDED,
		description: 'Local week year, unpadded',
	},
	{
		variableId: VAR_LOCAL_WEEK_YEAR_PADDED_4,
		value: LOCAL_WEEK_YEAR_PADDED_4,
		description: 'Local week year, padded to 4',
	},
	{
		variableId: VAR_LOCAL_WEEK_NUMBER_UNPADDED,
		value: LOCAL_WEEK_NUMBER_UNPADDED,
		description: 'Local week number, unpadded',
	},
	{
		variableId: VAR_LOCAL_WEEK_NUMBER_PADDED_2,
		value: LOCAL_WEEK_NUMBER_PADDED_2,
		description: 'Local week number, padded to 2',
	},
	{
		variableId: VAR_ORDINAL_DAY_OF_YEAR_UNPADDED,
		value: ORDINAL_DAY_OF_YEAR_UNPADDED,
		description: 'ordinal (day of year), unpadded',
	},
	{
		variableId: VAR_ORDINAL_DAY_OF_YEAR_PADDED_3,
		value: ORDINAL_DAY_OF_YEAR_PADDED_3,
		description: 'ordinal (day of year), padded to 3',
	},
	{ variableId: VAR_QUARTER_UNPADDED, value: QUARTER_UNPADDED, description: 'quarter, unpadded' },
	{ variableId: VAR_QUARTER_PADDED_2, value: QUARTER_PADDED_2, description: 'quarter, padded to 2' },
	{ variableId: VAR_LOCALIZED_NUMERIC_DATE, value: LOCALIZED_NUMERIC_DATE, description: 'localized numeric date' },
	{
		variableId: VAR_LOCALIZED_DATE_ABBREVIATED_MONTH,
		value: LOCALIZED_DATE_ABBREVIATED_MONTH,
		description: 'localized date with abbreviated month',
	},
	{
		variableId: VAR_LOCALIZED_DATE_FULL_MONTH,
		value: LOCALIZED_DATE_FULL_MONTH,
		description: 'localized date with full month',
	},
	{
		variableId: VAR_LOCALIZED_DATE_FULL_MONTH_WEEKDAY,
		value: LOCALIZED_DATE_FULL_MONTH_WEEKDAY,
		description: 'localized date with full month and weekday',
	},
	{ variableId: VAR_LOCALIZED_TIME, value: LOCALIZED_TIME, description: 'localized time' },
	{
		variableId: VAR_LOCALIZED_TIME_WITH_SECONDS,
		value: LOCALIZED_TIME_WITH_SECONDS,
		description: 'localized time with seconds',
	},
	{
		variableId: VAR_LOCALIZED_TIME_SECONDS_ABBREVIATED_OFFSET,
		value: LOCALIZED_TIME_SECONDS_ABBREVIATED_OFFSET,
		description: 'localized time with seconds and abbreviated offset',
	},
	{
		variableId: VAR_LOCALIZED_TIME_SECONDS_FULL_OFFSET,
		value: LOCALIZED_TIME_SECONDS_FULL_OFFSET,
		description: 'localized time with seconds and full offset',
	},
	{ variableId: VAR_LOCALIZED_24_HOUR_TIME, value: LOCALIZED_24_HOUR_TIME, description: 'localized 24-hour time' },
	{
		variableId: VAR_LOCALIZED_24_HOUR_TIME_WITH_SECONDS,
		value: LOCALIZED_24_HOUR_TIME_WITH_SECONDS,
		description: 'localized 24-hour time with seconds',
	},
	{
		variableId: VAR_LOCALIZED_24_HOUR_TIME_SECONDS_ABBREVIATED_OFFSET,
		value: LOCALIZED_24_HOUR_TIME_SECONDS_ABBREVIATED_OFFSET,
		description: 'localized 24-hour time with seconds and abbreviated offset',
	},
	{
		variableId: VAR_LOCALIZED_24_HOUR_TIME_SECONDS_FULL_OFFSET,
		value: LOCALIZED_24_HOUR_TIME_SECONDS_FULL_OFFSET,
		description: 'localized 24-hour time with seconds and full offset',
	},
	{
		variableId: VAR_SHORT_LOCALIZED_DATE_TIME,
		value: SHORT_LOCALIZED_DATE_TIME,
		description: 'short localized date and time',
	},
	{
		variableId: VAR_LESS_SHORT_LOCALIZED_DATE_TIME,
		value: LESS_SHORT_LOCALIZED_DATE_TIME,
		description: 'less short localized date and time',
	},
	{
		variableId: VAR_VERBOSE_LOCALIZED_DATE_TIME,
		value: VERBOSE_LOCALIZED_DATE_TIME,
		description: 'verbose localized date and time',
	},
	{
		variableId: VAR_EXTRA_VERBOSE_LOCALIZED_DATE_TIME,
		value: EXTRA_VERBOSE_LOCALIZED_DATE_TIME,
		description: 'extra verbose localized date and time',
	},
	{
		variableId: VAR_SHORT_LOCALIZED_DATE_TIME_WITH_SECONDS,
		value: SHORT_LOCALIZED_DATE_TIME_WITH_SECONDS,
		description: 'short localized date and time with seconds',
	},
	{
		variableId: VAR_LESS_SHORT_LOCALIZED_DATE_TIME_WITH_SECONDS,
		value: LESS_SHORT_LOCALIZED_DATE_TIME_WITH_SECONDS,
		description: 'less short localized date and time with seconds',
	},
	{
		variableId: VAR_VERBOSE_LOCALIZED_DATE_TIME_WITH_SECONDS,
		value: VERBOSE_LOCALIZED_DATE_TIME_WITH_SECONDS,
		description: 'verbose localized date and time with seconds',
	},
	{
		variableId: VAR_EXTRA_VERBOSE_LOCALIZED_DATE_TIME_WITH_SECONDS,
		value: EXTRA_VERBOSE_LOCALIZED_DATE_TIME_WITH_SECONDS,
		description: 'extra verbose localized date and time with seconds',
	},
	{ variableId: VAR_UNIX_TIMESTAMP_SECONDS, value: UNIX_TIMESTAMP_SECONDS, description: 'unix timestamp in seconds' },
	{
		variableId: VAR_UNIX_TIMESTAMP_MILLISECONDS,
		value: UNIX_TIMESTAMP_MILLISECONDS,
		description: 'unix timestamp in milliseconds',
	},
]
