export class FormatToken {
	public value: string
	public description: string

	constructor(token: string, description: string) {
		this.value = token
		this.description = description
	}
}

export const FormatTokens: Array<FormatToken> = [
	{ value: 'S', description: 'millisecond, unpadded' },
	{ value: 'SSS', description: 'millisecond, padded to 3' },
	{ value: 'u', description: 'fractional seconds, functionally identical to SSS' },
	{ value: 'uu', description: 'fractional seconds, between 0 and 99, padded to 2' },
	{ value: 'uuu', description: 'fractional seconds, between 0 and 9' },
	{ value: 's', description: 'second, unpadded' },
	{ value: 'ss', description: 'second, padded to 2' },
	{ value: 'm', description: 'minute, unpadded' },
	{ value: 'mm', description: 'minute, padded to 2' },
	{ value: 'h', description: 'hour, in 12-hour time, unpadded' },
	{ value: 'hh', description: 'hour, in 12-hour time, padded to 2' },
	{ value: 'H', description: 'hour, in 24-hour time, unpadded' },
	{ value: 'HH', description: 'hour, in 24-hour time, padded to 2' },
	{ value: 'Z', description: 'narrow offset' },
	{ value: 'ZZ', description: 'short offset' },
	{ value: 'ZZZ', description: 'techie offset' },
	{ value: 'ZZZZ', description: 'abbreviated named offset' },
	{ value: 'ZZZZZ', description: 'unabbreviated named offset' },
	{ value: 'z', description: 'IANA zone' },
	{ value: 'a', description: 'meridiem' },
	{ value: 'd', description: 'day of the month, unpadded' },
	{ value: 'dd', description: 'day of the month, padded to 2' },
	{ value: 'E', description: 'day of the week, as number from 1-7 (Monday is 1, Sunday is 7)' },
	{ value: 'EEE', description: 'day of the week, as an abbreviate localized string' },
	{ value: 'EEEE', description: 'day of the week, as an unabbreviated localized string' },
	{ value: 'EEEEE', description: 'day of the week, as a single localized letter' },
	{ value: 'M', description: 'month, unpadded' },
	{ value: 'MM', description: 'month, padded to 2' },
	{ value: 'MMM', description: 'month, as an abbreviated localized string' },
	{ value: 'MMMM', description: 'month, as an unabbreviated localized string' },
	{ value: 'MMMMM', description: 'month as a single localized letter' },
	{ value: 'y', description: 'year, unpadded' },
	{ value: 'yy', description: 'year, two-digit' },
	{ value: 'yyyy', description: 'year, four- to six-digit, padded to 4' },
	{ value: 'G', description: 'abbreviated localized era' },
	{ value: 'GG', description: 'unabbreviated localized era' },
	{ value: 'GGGGG', description: 'one-letter localized era' },
	{ value: 'kk', description: 'ISO week year, unpadded' },
	{ value: 'kkkk', description: 'ISO week year, padded to 4' },
	{ value: 'W', description: 'ISO week number, unpadded' },
	{ value: 'WW', description: 'ISO week number, padded to 2' },
	{ value: 'ii', description: 'Local week year, unpadded' },
	{ value: 'iiii', description: 'Local week year, padded to 4' },
	{ value: 'n', description: 'Local week number, unpadded' },
	{ value: 'nn', description: 'Local week number, padded to 2' },
	{ value: 'o', description: 'ordinal (day of year), unpadded' },
	{ value: 'ooo', description: 'ordinal (day of year), padded to 3' },
	{ value: 'q', description: 'quarter, unpadded' },
	{ value: 'qq', description: 'quarter, padded to 2' },
	{ value: 'D', description: 'localized numeric date' },
	{ value: 'DD', description: 'localized date with abbreviated month' },
	{ value: 'DDD', description: 'localized date with full month' },
	{ value: 'DDDD', description: 'localized date with full month and weekday' },
	{ value: 't', description: 'localized time' },
	{ value: 'tt', description: 'localized time with seconds' },
	{ value: 'ttt', description: 'localized time with seconds and abbreviated offset' },
	{ value: 'tttt', description: 'localized time with seconds and full offset' },
	{ value: 'T', description: 'localized 24-hour time' },
	{ value: 'TT', description: 'localized 24-hour time with seconds' },
	{ value: 'TTT', description: 'localized 24-hour time with seconds and abbreviated offset' },
	{ value: 'TTTT', description: 'localized 24-hour time with seconds and full offset' },
	{ value: 'f', description: 'short localized date and time' },
	{ value: 'ff', description: 'less short localized date and time' },
	{ value: 'fff', description: 'verbose localized date and time' },
	{ value: 'ffff', description: 'extra verbose localized date and time' },
	{ value: 'F', description: 'short localized date and time with seconds' },
	{ value: 'FF', description: 'less short localized date and time with seconds' },
	{ value: 'FFF', description: 'verbose localized date and time with seconds' },
	{ value: 'FFFF', description: 'extra verbose localized date and time with seconds' },
	{ value: 'X', description: 'unix timestamp in seconds' },
	{ value: 'x', description: 'unix timestamp in milliseconds' },
]
